### ISSUE TITLE
Setting up cluster mode problem

### ISSUE THREAD

**Issue by apprithm** [tinode/chat#230]
### Subject of the issue
Im not sure if this is a bug or Im not setting it up correctly.

I have 3 docker containers each of them exposed port 12001 and mapped to hose 6060, 6061, 6062 respectively. Their hostnames are tinode-srv-1, tinode-srv-2, tinode-srv-3

In the config file I have the following setup for the cluster address:
			{"name": "one", "addr":"tinode-srv-1:12001"},
			{"name": "two", "addr":"tinode-srv-2:12001"},
			{"name": "three", "addr":"tinode-srv-3:12001"}

Im able to visit the JS browser client at localhost:6060(or 6061, 6062) and login with my credentials. But whenever I click a contact, the chat window will always stuck in loading, neither Im able to send any message.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform Mac
  * version of tinode server, e.g. `0.15.13`
  * database backend  mysql
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version: Chrome

### Expected behaviour
Open the chat window and see chat history, send message

### Actual behaviour
Stuck in loading

### Server-side log
```
2019/04/07 09:01:23 cluster: connection to 'two' established
2019/04/07 09:02:09 cluster: connection to 'three' established
12019/04/07 09:02:23 cluster: forwarding request to node 'three'
2019/04/07 09:02:24 ws: session started hi3eSCXxP-s 2
2019/04/07 09:02:24 in: '{"hi":{"id":"109164","ver":"0.15.13","ua":"TinodeWeb/0.15.13 (Chrome/73.0; MacIntel); tinodejs/0.15.13","lang":"en-US"}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid=''
2019/04/07 09:02:24 in: '{"login":{"id":"109165","scheme":"token","secret":"HNbsrJn3djBQLrxcFAABAAEAs8aPSTAtWuMw9ImeFXigr6dj4NYYgRdeXXVSSe/T39Y="}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid=''
2019/04/07 09:02:24 in: '{"sub":{"id":"109166","topic":"me","get":{"what":"sub desc"}}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid='HNbsrJn3djA'
2019/04/07 09:02:24 in: '{"sub":{"id":"109167","topic":"usrqyfdxa20wUI","get":{"data":{"limit":24},"sub":{"ims":"2019-04-06T22:17:04.416Z"},"desc":{"ims":"2019-04-06T22:17:04.416Z"},"what":"data sub desc"}}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid='HNbsrJn3djA'
2019/04/07 09:02:24 cluster: forwarding request to node 'three'
2019/04/07 09:02:24 cluster: response from Master for session hi3eSCXxP-s
2019/04/07 09:02:25 in: '{"sub":{"id":"109168","topic":"usr35IOhSyrFKU","get":{"data":{"limit":24},"sub":{"ims":"2019-04-06T22:16:40.384Z"},"desc":{"ims":"2019-04-06T22:16:40.384Z"},"what":"data sub desc"}}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid='HNbsrJn3djA'
2019/04/07 09:02:25 cluster: forwarding request to node 'two'
2019/04/07 09:02:25 cluster: response from Master for session hi3eSCXxP-s
2019/04/07 09:02:26 in: '{"sub":{"id":"109169","topic":"usrqyfdxa20wUI","get":{"data":{"limit":24},"sub":{"ims":"2019-04-06T22:17:04.416Z"},"desc":{"ims":"2019-04-06T22:17:04.416Z"},"what":"data sub desc"}}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid='HNbsrJn3djA'
2019/04/07 09:02:26 cluster: forwarding request to node 'three'
2019/04/07 09:02:26 cluster: response from Master for session hi3eSCXxP-s
2019/04/07 09:02:31 cluster: forwarding request to node 'two'
2019/04/07 09:02:35 ws: session started ydMv088b7Vk 2
2019/04/07 09:02:35 in: '{"hi":{"id":"130542","ver":"0.15.13","ua":"TinodeWeb/0.15.13 (Chrome/73.0; MacIntel); tinodejs/0.15.13","lang":"en-US"}}' ip='172.18.0.1:33290' sid='ydMv088b7Vk' uid=''
2019/04/07 09:02:35 in: '{"login":{"id":"130543","scheme":"basic","secret":"amFzb246MTIzNDU2"}}' ip='172.18.0.1:33290' sid='ydMv088b7Vk' uid=''
2019/04/07 09:02:36 in: '{"sub":{"id":"130544","topic":"me","get":{"what":"sub desc"}}}' ip='172.18.0.1:33290' sid='ydMv088b7Vk' uid='HNbsrJn3djA'
2019/04/07 09:02:39 in: '{"sub":{"id":"130545","topic":"fnd","get":{"what":"tags"}}}' ip='172.18.0.1:33290' sid='ydMv088b7Vk' uid='HNbsrJn3djA'
2019/04/07 09:02:39 cluster: forwarding request to node 'three'
2019/04/07 09:02:39 cluster: response from Master for session ydMv088b7Vk
2019/04/07 09:02:42 in: '{"sub":{"id":"130546","topic":"usrqyfdxa20wUI","get":{"data":{"limit":24},"sub":{"ims":"2019-04-06T22:17:04.416Z"},"desc":{"ims":"2019-04-06T22:17:04.416Z"},"what":"data sub desc"}}}' ip='172.18.0.1:33290' sid='ydMv088b7Vk' uid='HNbsrJn3djA'
2019/04/07 09:02:42 cluster: forwarding request to node 'three'
2019/04/07 09:02:43 in: '{"sub":{"id":"130547","topic":"fnd","get":{"what":"tags"}}}' ip='172.18.0.1:33290' sid='ydMv088b7Vk' uid='HNbsrJn3djA'
2019/04/07 09:02:43 cluster: forwarding request to node 'three'
2019/04/07 09:02:43 cluster: response from Master for session ydMv088b7Vk
2019/04/07 09:02:44 ws: readLoop ydMv088b7Vk websocket: close 1005 (no status)
2019/04/07 09:02:44 cluster: forwarding request to node 'three'
2019/04/07 09:02:49 ws: session started _4eGa7zRzXk 2
2019/04/07 09:02:49 in: '{"hi":{"id":"82201","ver":"0.15.13","ua":"TinodeWeb/0.15.13 (Chrome/73.0; MacIntel); tinodejs/0.15.13","lang":"en-US"}}' ip='172.18.0.1:33292' sid='_4eGa7zRzXk' uid=''
2019/04/07 09:02:49 in: '{"login":{"id":"82202","scheme":"basic","secret":"Ym9iOjEyMzQ1Ng=="}}' ip='172.18.0.1:33292' sid='_4eGa7zRzXk' uid=''
2019/04/07 09:02:49 in: '{"sub":{"id":"82203","topic":"me","get":{"what":"sub desc"}}}' ip='172.18.0.1:33292' sid='_4eGa7zRzXk' uid='qyfdxa20wUI'
2019/04/07 09:02:49 cluster: forwarding request to node 'three'
2019/04/07 09:02:49 cluster: response from Master for session _4eGa7zRzXk
2019/04/07 09:04:12 in: '{"sub":{"id":"109170","topic":"usr35IOhSyrFKU","get":{"data":{"limit":24},"sub":{"ims":"2019-04-06T22:16:40.384Z"},"desc":{"ims":"2019-04-06T22:16:40.384Z"},"what":"data sub desc"}}}' ip='172.18.0.1:33284' sid='hi3eSCXxP-s' uid='HNbsrJn3djA'
```

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/86e812bf852742590d1b8b1d873a001de7297d38

**Comment by apprithm** [comment]
@or-else 
I have pulled the latest devel branch last commit 59cfff510242ea34974d7a07a76b55d5b3d346ce , then I built docker images via docker-build.sh. With the new image, I'm still having the same problem.

**Comment by or-else** [comment]
Docker script pulls pre-built binaries from GitHub. Those binaries are not yet fixed. You have to build it yourself or wait for the next release.

**Comment by apprithm** [comment]
@or-else I see.
I tried to use build-all.sh, but Im not able to execute the final binary.
Im using a macbook pro.

Here is the GOX settings I'm using:
```
# Supported OSs: darwin windows linux
goplat=( darwin )
# Supported CPU architectures: amd64
goarc=( 386 )     <-I tried 386, amd64 and i386
# Supported database tags
dbtags=( mysql )
```
Are those correct ?

**Comment by or-else** [comment]
Just wait a couple of hours. I'll make a release.

**Comment by or-else** [comment]
BTW, you don't need gox etc. They are only useful for cross-compiling. Just follow these instructions:
https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source

**Comment by or-else** [comment]
I believe the issue is resolved and the fix released. Is there anything else with respect to this issue?
