### ISSUE TITLE
Long Polling respond status 200 but body is empty

### ISSUE THREAD

**Issue by wmshek1992** [tinode/chat#406]
### Long Polling respond status 200 but body is empty

I would like to develop an own client application with either long polling or websocket. But encounter some problems in long-polling.

First, I tried to play with long-polling in the sandbox, using the default accounts.
It is fine when using websocket but not by using long polling.
a loading gif appears but the login don't proceed further in the sandbox. 
![Screenshot 2020-04-02 at 11 26 20 AM](https://user-images.githubusercontent.com/46838582/78209673-3b038380-74da-11ea-8fe8-e0f049563c10.png)

Second, I tried to connect to the endpoint of my setup in docker by using postman.
http://<host>/v0/channels/lp?apikey=<key>
i.  create a session and ctrl message with sid received.
ii. POST a {"hi":{ "ver": "123"} } to the server via long polling url, response with status OK with 
iii. POST {login} packet or any other packet to long-polling endpoint, received status OK empty body, but the login should have be successful because I see uid appears in the session. 
iv. Then I sent '{"sub":{"topic":"me","get":{"what":"sub desc tags cred"}}}', again, received status OK empty body. 

Should I expect a HTTP response carrying the info I asked for in "get"?
Or I am doing it incorrectly?

### Is this a bug report of a feature request?
- [X] Bug report
- [ ] Feature request

#### Server-side
 docker with latest Tinode version
  
#### Client-side
Postman

## Tinode log
2020/04/02 03:45:14 longPoll: session started mjljXqKdgH0 5
2020/04/02 03:45:20 in: '{"hi":{ "ver": "0.16.4"} }' ip='42.2.242.174:56539' sid='mjljXqKdgH0' uid=''
2020/04/02 03:45:28 in: '{"login":{"id":"98352","scheme":"basic","secret":"ZGF2ZTpkYXZlMTIz"}}' ip='42.2.242.174:56539' sid='mjljXqKdgH0' uid=''
2020/04/02 03:45:38 in: '{"sub":{"id":"98353","topic":"me","get":{"what":"sub desc tags cred"}}}' ip='42.2.242.174:56539' sid='mbH8CZPe4Fc' uid='fw-qpf5vbV8'
2020/04/02 03:54:37 in: '{"sub":{"topic":"me","get":{"what":"sub desc tags cred"}}}' ip='42.2.242.174:56539' sid='mbH8CZPe4Fc' uid='fw-qpf5vbV8'

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tinode-js/commit/ed2a8c3ce3d52a41b06a15ae4934864f9e752452

**Comment by wmshek1992** [comment]
Thanks!

This is a fix in client webapp, right?

May I have your comment on my steps on the {sub} packet on long-polling endpoint with empty response body please? 

> iv. Then I sent '{"sub":{"topic":"me","get":{"what":"sub desc tags cred"}}}', again, received status OK empty body.

**Comment by or-else** [comment]
Yes, it was in javascript SDK.
Can you reproduce the problem with the updated code?

**Comment by wmshek1992** [comment]
I am sorry I am using docker version, it may take a while for me to build one with updated code.

**Comment by or-else** [comment]
Docker with the fix has been released as 0.16.5-beta7

**Comment by AndreyB-zz** [comment]
> Thanks!
> 
> This is a fix in client webapp, right?
> 
> May I have your comment on my steps on the {sub} packet on long-polling endpoint with empty response body please?
> 
> > iv. Then I sent '{"sub":{"topic":"me","get":{"what":"sub desc tags cred"}}}', again, received status OK empty body.

Hi. Did you manage to use a Postman for this?

**Comment by farzamvat** [comment]
Hi, I encountered wmshek1992 problem. I did his scenario step by step with long polling url with postman client and I still get empty response.
Here is my tinode chat server v 0.17.10 logs:
I2021/12/14 14:35:34 longPoll: session started xYLD9AvRCIk 192.168.245.1:9148 65
I2021/12/14 14:36:57 in: '{"hi":{ "ver": "0.17.10"} }' sid='xYLD9AvRCIk' uid=''
I2021/12/14 14:37:17 in: '{"login":{"id":"98352","scheme":"basic","secret":"ZGF2ZTpkYXZlMTIz"}}' sid='xYLD9AvRCIk' uid=''
I2021/12/14 14:37:33 in: '{"sub":{"id":"98353","topic":"me","get":{"what":"sub desc tags cred"}}}' sid='xYLD9AvRCIk' uid='y2_oXObt3xw'
I2021/12/14 14:37:45 in: '{"sub":{"topic":"me","get":{"what":"sub desc tags cred"}}}' sid='xYLD9AvRCIk' uid='y2_oXObt3xw'

**Comment by or-else** [comment]
Can you reproduce the problem using Tinode Web?

**Comment by or-else** [comment]
I suspect you are trying to use the long polling endpoint as if it's a REST endpoint. It is not. Tinode API is asynchronous and an empty response over LP is expected.

And no, you do not have the same problem as wmshek1992 because that problem has been fixed.

**Comment by farzamvat** [comment]
I can see that you're right. As I know Tinode Web is using ws for communication, I got no problem with using websockets to communicate with Tinode chat server but using websockets in my scenario would put a burden on my resources so I prefer to use the LP option, but I really don't get it, if its async by essence its ok I get this but how I can query my topics or "me" topic using LP if the response is always empty?! P.S I have read the whole API documentation and I couldn't find any solution to query any data using LP.

**Comment by farzamvat** [comment]
I know this platform is not suitable for this kind of questions but as the community is limited and I couldnt find any solutions through web, I decided to ask it here. please accept my apologies

**Comment by or-else** [comment]
Please use forum for general discussions and questions: https://groups.google.com/d/forum/tinode
