### ISSUE TITLE
Cluster mode, group message sending error

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#420]
tinode version  v0.16.5-rc1
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xaf8bd1]

goroutine 1645 [running]:
main.(*Cluster).Route(0xc000074c80, 0xc0002a18c0, 0xc0002b5b13, 0x0, 0x0)
	/Users/mike/golang/poizon/duims/cluster.go:411 +0x51
reflect.Value.call(0xc0000be780, 0xc0000bc650, 0x13, 0xd608d2, 0x4, 0xc0001b3f08, 0x3, 0x3, 0x0, 0x0, ...)
	/Users/mike/.gvm/gos/go1.14.1/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0xc0000be780, 0xc0000bc650, 0x13, 0xc0001ed708, 0x3, 0x3, 0x0, 0x0, 0x0)
	/Users/mike/.gvm/gos/go1.14.1/src/reflect/value.go:321 +0xb4
net/rpc.(*service).call(0xc0000c1bc0, 0xc000074050, 0xc0001900c8, 0xc0001900f0, 0xc00010e380, 0xc0001d3240, 0xbbf1a0, 0xc0002a18c0, 0x16, 0xbb21e0, ...)
	/Users/mike/.gvm/gos/go1.14.1/src/net/rpc/server.go:377 +0x17f
created by net/rpc.(*Server).ServeCodec
	/Users/mike/.gvm/gos/go1.14.1/src/net/rpc/server.go:474 +0x42b
```

meesage err:
```
panic: interface conversion: interface {} is []uint8, not *main.ServerComMessage

goroutine 218 [running]:
main.(*Session).rpcWriteLoop(0xc000456140)
	/Users/mike/golang/poizon/duims/cluster.go:764 +0x60e
created by main.(*Cluster).Master
	/Users/mike/golang/poizon/duims/cluster.go:363 +0x46f
2020/04/14 20:41:21 Server v0.16:/data/tinode/duims-linux:undef; pid 6511; 4 process(es)
```

**Comment by or-else** [comment]
Please show entire server-side log prior to the crash.

**Comment by or-else** [comment]
The first crash `/Users/mike/golang/poizon/duims/cluster.go:411 +0x51` is quite obvious. I'll fix it now.

I still need logs for the second one. Something like that has been fixed recently: 
https://github.com/tinode/chat/commit/774980a860e989e1238f63c1493dbd4cc3578f39#diff-d412b9240514b30a308e4b4c8208ae72L395
It's not clear to me how it is possible to get it again.

**Comment by or-else** [comment]
The first crash is fixed: https://github.com/tinode/chat/commit/db431ba8429a54eb5d68daf79682adf0a6419ff6

As for the second crash, is it possible that you were running some cluster nodes at a version below 0.16.5-rc1?

**Comment by hhy5861** [comment]
```
2020/04/14 10:46:52 cluster Master: session signature mismatch vUMiCuaP4ic
2020/04/14 10:46:52 cluster Master: session signature mismatch US9e_fPJv-Q
2020/04/14 10:46:52 cluster: session proxy started PuLJrY4Uvqo 1
2020/04/14 10:46:52 cluster: session proxy started WwQ0NehSWnA 2
2020/04/14 10:46:52 hub: failed to load or create topic: grp6QEVhmU1Wrw topic not found
2020/04/14 10:46:52 cluster: session proxy closed PuLJrY4Uvqo
panic: interface conversion: interface {} is []uint8, not *main.ServerComMessage

goroutine 71 [running]:
main.(*Session).rpcWriteLoop(0xc0003ba280)
        /Users/mike/golang/poizon/duims/cluster.go:764 +0x605
created by main.(*Cluster).Master
        /Users/mike/golang/poizon/duims/cluster.go:363 +0x46f
```

In addition：
Can a group support 50,000 to 100,000 members online?

**Comment by or-else** [comment]
Please answer this question:

> As for the second crash, is it possible that you were running some cluster nodes at a version below 0.16.5-rc1?

**Comment by or-else** [comment]
> Can a group support 50,000 to 100,000 members online?

You may try but probably not. We are working on it right now:
https://github.com/tinode/chat/tree/topic-proxy
I expect it to be ready in 2-3 months.

**Comment by hhy5861** [comment]
> Please answer this question:
> 
> > As for the second crash, is it possible that you were running some cluster nodes at a version below 0.16.5-rc1?

Yes，version 0.16.5-rc1

**Comment by or-else** [comment]
> Yes，version 0.16.5-rc1

Do you mean "Yes, all at -rc1" or "Yes, some could be below -rc1"?

**Comment by or-else** [comment]
And please show longer log prior to the crash.

**Comment by or-else** [comment]
It would also be useful to see logs from other cluster nodes at the time of the crash.

**Comment by hhy5861** [comment]
> It would also be useful to see logs from other cluster nodes at the time of the crash.

I encountered this problem should be solved in the topic-proxy branch.

**Comment by or-else** [comment]
> I encountered this problem should be solved in the topic-proxy branch.

As far as I can tell it's been solved in 774980a. The most likely source of the problem is that one of the nodes in your cluster was at a version lower than 0.16.5-rc1. 

The `topic-proxy` is meant to refactor a lot of code but probably not this one.

**Comment by hhy5861** [comment]
> > I encountered this problem should be solved in the topic-proxy branch.
> 
> As far as I can tell it's been solved in [774980a](https://github.com/tinode/chat/commit/774980a860e989e1238f63c1493dbd4cc3578f39). The most likely source of the problem is that one of the nodes in your cluster was at a version lower than 0.16.5-rc1.
> 
> The `topic-proxy` is meant to refactor a lot of code but probably not this one.

When will a stable version of cluster communication be released?

**Comment by or-else** [comment]
Next week.

**Comment by hhy5861** [comment]
I found a problem. When there are more than 3000+ connections, the (pub) event cannot be sent. Should this be a service configuration issue?

**Comment by or-else** [comment]
3000 connection to a cluster with three nodes? Then you are probably hitting the limit on the number of file descriptors per process in your host: 
https://docs.oracle.com/cd/E19476-01/821-0505/file-descriptor-requirements.html
https://www.cyberciti.biz/tips/linux-procfs-file-descriptors.html

Tinode itself has no limit on the number of sessions.

**Comment by hhy5861** [comment]
> 3000 connection to a cluster with three nodes? Then you are probably hitting the limit on the number of file descriptors per process in your host:
> https://docs.oracle.com/cd/E19476-01/821-0505/file-descriptor-requirements.html
> https://www.cyberciti.biz/tips/linux-procfs-file-descriptors.html
> 
> Tinode itself has no limit on the number of sessions.

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 125879
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 125879
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I do n’t think it ’s a problem with the system itself, I ’m checking!

**Comment by or-else** [comment]
Did you also check `/proc/sys/fs/file-max` and `/etc/security/limits.conf` ?

**Comment by hhy5861** [comment]
> Did you also check `/proc/sys/fs/file-max` and `/etc/security/limits.conf` ?

file-max:
1507240

limits.conf:
![image](https://user-images.githubusercontent.com/8274977/79584017-62746600-8100-11ea-8c11-29379eb27188.png)

**Comment by or-else** [comment]
Well, figure it out. If you run docker check `/etc/init/docker.conf`.

We are not limiting the number of connections in any way.

**Comment by hhy5861** [comment]
> Well, figure it out. If you run docker check `/etc/init/docker.conf`.
> 
> We are not limiting the number of connections in any way.

android Ios sdk:
D/Tinode: out: {"sub":{"bkg":false,"get":{"what":"sub"},"id":"103353","topic":"me"}}
D/PromisedReply: REJECTING promise co.tinode.tinodesdk.PromisedReply@9237d2f
    co.tinode.tinodesdk.ServerResponseException: timeout (504)

**Comment by or-else** [comment]
What do you see in the server logs?

**Comment by or-else** [comment]
Can you define a way for me to reproduce the problem?

**Comment by hhy5861** [comment]
> Can you define a way for me to reproduce the problem?

this problem only occurs when there are 1000+ connections. There is no exception log in the server log.

**Comment by or-else** [comment]
Do you see the same problem when running a standalone server?

**Comment by or-else** [comment]
There is no limit on the number of sessions, but there are various other limits, such as size of the message, maximum number of subscribers per topic, maximum number of database results. Maybe you are hitting one of those limits.

**Comment by or-else** [comment]
I found another bug in the cluster which may affect you. I'll fix it later today.

**Comment by or-else** [comment]
This is the change: https://github.com/tinode/chat/commit/f4debee56bae939ba8ef93bb39144f094f5a7be6

**Comment by hhy5861** [comment]
```
2020/04/19 20:20:52 in: '{"pub":{"id":"92549","content":"{\"msg\":{\"count\":21}}","topic":"grp1bxU0S0uu-o","noecho":true,"head":{"cat":"3","ct":"1001"}}}' ip='100.97.134.10:3336' sid='rpHKBxCcUQM' uid='82UvwHnnIEw'
2020/04/19 20:20:52 No remote subscription (yet) for topic 'grp1bxU0S0uu-o', sid 'rpHKBxCcUQM'
2020/04/19 20:20:57 in: '{"pub":{"id":"92550","content":"{\"msg\":{\"count\":9}}","topic":"grp1bxU0S0uu-o","noecho":true,"head":{"cat":"3","ct":"1001"}}}' ip='100.97.134.10:3336' sid='rpHKBxCcUQM' uid='82UvwHnnIEw'
2020/04/19 20:20:57 No remote subscription (yet) for topic 'grp1bxU0S0uu-o', sid 'rpHKBxCcUQM'
```

**Comment by hhy5861** [comment]
![image](https://user-images.githubusercontent.com/8274977/79721020-4c3ef380-8314-11ea-9f66-21ff8ead8e8d.png)

**Comment by or-else** [comment]
Regarding
```
2020/04/19 20:20:52 in: '{"pub":{"id":"92549","content":"{\"msg\":{\"count\":21}}","topic":"grp1bxU0S0uu-o","noecho":true,"head":{"cat":"3","ct":"1001"}}}' ip='100.97.134.10:3336' sid='rpHKBxCcUQM' uid='82UvwHnnIEw'
2020/04/19 20:20:52 No remote subscription (yet) for topic 'grp1bxU0S0uu-o', sid 'rpHKBxCcUQM'
...
```
What's your question?

**Comment by or-else** [comment]
Regarding the crash, it seems like you are using `topic-proxy` branch. It's far from being complete and may have bugs including crashes.

**Comment by or-else** [comment]
Also, could you please post text logs instead of pictures?

**Comment by or-else** [comment]
It looks like the crash is in https://github.com/gorilla/websocket
You may want to report it there if it's reproducible.

**Comment by hhy5861** [comment]
> Regarding the crash, it seems like you are using `topic-proxy` branch. It's far from being complete and may have bugs including crashes.

I brought together topic-proxy. Because this branch solves the agency problem.

**Comment by hhy5861** [comment]
this also reported a thread safety issue？
```
2020/04/20 18:03:24 ws: session started 6rjHQQjZqCs 102
2020/04/20 18:03:24 ws: session started Ar52HQnBaEI 103
2020/04/20 18:03:24 ws: session started gzSd9zZo5fE 104
fatal error: concurrent map read and map write

goroutine 746 [running]:
runtime.throw(0xd85073, 0x21)
        /Users/mike/.gvm/gos/go1.14.1/src/runtime/panic.go:1114 +0x72 fp=0xc000609880 sp=0xc000609850 pc=0x434572
runtime.mapaccess2_faststr(0xc42320, 0xc0003e48d0, 0xc000414eb0, 0xb, 0xc0004334a0, 0xc0002885d0)
        /Users/mike/.gvm/gos/go1.14.1/src/runtime/map_faststr.go:116 +0x47c fp=0xc0006098f0 sp=0xc000609880 pc=0x41305c
main.(*SessionStore).NewSession(0xc0003b8ba0, 0xd54440, 0xc0004334a0, 0x0, 0x0, 0xc0004334a0, 0x0)
        /Users/mike/golang/github/chat/server/sessionstore.go:48 +0xb9 fp=0xc0006099b8 sp=0xc0006098f0 pc=0xb35b09
main.serveWebSocket(0xeb7100, 0xc0004a4460, 0xc0000a6500)
        /Users/mike/golang/github/chat/server/hdl_websock.go:161 +0x4bb fp=0xc000609b60 sp=0xc0006099b8 pc=0xb0c68b
net/http.HandlerFunc.ServeHTTP(0xdb35c8, 0xeb7100, 0xc0004a4460, 0xc0000a6500)
        /Users/mike/.gvm/gos/go1.14.1/src/net/http/server.go:2012 +0x44 fp=0xc000609b88 sp=0xc000609b60 pc=0x717e54
net/http.(*ServeMux).ServeHTTP(0xc0002b4f40, 0xeb7100, 0xc0004a4460, 0xc0000a6500)
        /Users/mike/.gvm/gos/go1.14.1/src/net/http/server.go:2387 +0x1a5 fp=0xc000609be8 sp=0xc000609b88 pc=0x719c95
```

**Comment by or-else** [comment]
> fatal error: concurrent map read and map write

fixed: https://github.com/tinode/chat/commit/8df04eb3615bb160e546d7db79e17aaa4dd5094f

**Comment by hhy5861** [comment]
Will the issue I encounter be released in a stable version this week? I suggest to unify the recovery when adding the panic to the http server and not letting the service hang up.

**Comment by hhy5861** [comment]
I found a very serious problem that will not release the connection. The client has been disconnected for 1 hour, but the connection still exists.

**Comment by or-else** [comment]
> Will the issue I encounter be released in a stable version this week?

The `devel` branch will be released this week. The `topic-proxy` will not be released.

> I suggest to unify the recovery when adding the panic to the http server and not letting the service hang up.

I don't understand.

> I found a very serious problem that will not release the connection.

This is not actionable.

**Comment by hhy5861** [comment]
In this cluster mode, some people in the group chat cannot receive information. Topic-proxy branch I used.

Will a stable version of cluster routing be issued today?

**Comment by or-else** [comment]
https://github.com/tinode/chat/releases/tag/v0.16.5
https://hub.docker.com/u/tinode

**Comment by or-else** [comment]
All the bugs reported in this issue that I could reproduce are fixed and fixes are releases. If you continue to have problems, please open another issue.
