### ISSUE TITLE
The .github/workflows/fix-typos.yml is broken

### ISSUE THREAD

**Issue by or-else** [tinode/chat#803]
The [.github/workflows/fix-typos.yml](https://github.com/tinode/chat/blob/master/.github/workflows/fix-typos.yml) has been [failing](https://github.com/tinode/chat/actions/workflows/fix-typos.yml) for the past two weeks. 

@stavares843 could you please take a look. Thanks!

**Comment by stavares843** [comment]
fixed here 🔨 

https://github.com/tinode/chat/pull/804 cc @or-else

**Comment by or-else** [comment]
Thanks! Merged.

**Comment by or-else** [comment]
Actually, it's still failing. I re-run the job and it produced the same error.

**Comment by or-else** [comment]
```
ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/inspect.py)
Error: The process '/opt/hostedtoolcache/Python/3.11.0/x64/bin/python' failed with exit code 1
```

**Comment by stavares843** [comment]
maybe was a old CI job? is green [here](https://github.com/tinode/chat/actions/runs/3519286123/jobs/5899078479)

**Comment by or-else** [comment]
OK, thanks.
